packages:
  - packages/**/**

catalog:
  vite: npm:vite@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@^0.1.14

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
