packages:
  - packages/*
  - packages/*/*

catalog:
  vite: npm:vite@latest
  vite-plus: 0.1.13
  vitest: npm:@voidzero-dev/vite-plus-test@^0.1.14

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
