// This file is auto-generated by vite-plugin-route-builder
// Do not edit manually
/* eslint-disable */
// @ts-nocheck

import type { RouteObject } from "react-router"

// Imports for page components
const lazy0 = () => import("./pages/chat/ChatHistoryPanel")
const lazy1 = () => import("./pages/chat/ChatMessage")
const lazy2 = () => import("./pages/chat/StatusBar")
const lazy3 = () => import("./pages/chat/ThinkingPanel")
const lazy4 = () => import("./pages/chat/ToolWriteApprovalDialog")
const lazy5 = () => import("./pages/chat/index")
const lazy6 = () => import("./pages/files/index")
const lazy7 = () => import("./pages/transcript/file/[id]")
const lazy8 = () => import("./pages/transcript/live")
const lazy9 = () => import("./pages/transcript/index")
const lazy10 = () => import("./pages/index")

// Generated route configuration
export const routes: RouteObject[] = [
  {
    "path": "chat",
    "children": [
      {
        "path": "ChatHistoryPanel",
        "lazy": lazy0
      },
      {
        "path": "ChatMessage",
        "lazy": lazy1
      },
      {
        "path": "StatusBar",
        "lazy": lazy2
      },
      {
        "path": "ThinkingPanel",
        "lazy": lazy3
      },
      {
        "path": "ToolWriteApprovalDialog",
        "lazy": lazy4
      },
      {
        "path": "",
        "lazy": lazy5
      }
    ]
  },
  {
    "path": "files",
    "children": [
      {
        "path": "",
        "lazy": lazy6
      }
    ]
  },
  {
    "path": "transcript",
    "children": [
      {
        "path": "file",
        "children": [
          {
            "path": ":id",
            "lazy": lazy7
          }
        ]
      },
      {
        "path": "live",
        "lazy": lazy8
      },
      {
        "path": "",
        "lazy": lazy9
      }
    ]
  },
  {
    "path": "",
    "lazy": lazy10
  }
]

export default routes
