export interface NemotronLanguage {
  id: number;
  label: string;
}

// The model's supported `lang_id` values, keyed by BCP-47-ish language code.
export const NEMOTRON_LANGUAGE_BY_CODE: Record<string, NemotronLanguage> = {
  en: { id: 0, label: "English (default / US)" },
  "en-US": { id: 0, label: "English (United States)" },
  "en-GB": { id: 1, label: "English (United Kingdom)" },
  "es-ES": { id: 2, label: "Spanish (Spain)" },
  es: { id: 3, label: "Spanish (default / Latin America)" },
  "es-US": { id: 3, label: "Spanish (US Latin American)" },
  zh: { id: 4, label: "Chinese (Mandarin, Simplified)" },
  "zh-CN": { id: 4, label: "Chinese (Mandarin, Simplified)" },
  hi: { id: 6, label: "Hindi" },
  "hi-IN": { id: 6, label: "Hindi (India)" },
  ar: { id: 7, label: "Arabic" },
  "ar-AR": { id: 7, label: "Arabic" },
  fr: { id: 8, label: "French (default / France)" },
  "fr-FR": { id: 8, label: "French (France)" },
  de: { id: 9, label: "German" },
  "de-DE": { id: 9, label: "German (Germany)" },
  ja: { id: 10, label: "Japanese" },
  "ja-JP": { id: 10, label: "Japanese" },
  ru: { id: 11, label: "Russian" },
  "ru-RU": { id: 11, label: "Russian" },
  "pt-BR": { id: 12, label: "Portuguese (Brazil)" },
  pt: { id: 13, label: "Portuguese (default / Portugal)" },
  "pt-PT": { id: 13, label: "Portuguese (Portugal)" },
  ko: { id: 14, label: "Korean" },
  "ko-KR": { id: 14, label: "Korean (South Korea)" },
  it: { id: 15, label: "Italian" },
  "it-IT": { id: 15, label: "Italian" },
  nl: { id: 16, label: "Dutch" },
  "nl-NL": { id: 16, label: "Dutch (Netherlands)" },
  pl: { id: 17, label: "Polish" },
  "pl-PL": { id: 17, label: "Polish" },
  tr: { id: 18, label: "Turkish" },
  "tr-TR": { id: 18, label: "Turkish" },
  uk: { id: 19, label: "Ukrainian" },
  "uk-UA": { id: 19, label: "Ukrainian" },
  ro: { id: 20, label: "Romanian" },
  "ro-RO": { id: 20, label: "Romanian" },
  el: { id: 21, label: "Greek" },
  "el-GR": { id: 21, label: "Greek" },
  cs: { id: 22, label: "Czech" },
  "cs-CZ": { id: 22, label: "Czech" },
  hu: { id: 23, label: "Hungarian" },
  "hu-HU": { id: 23, label: "Hungarian" },
  sv: { id: 24, label: "Swedish" },
  "sv-SE": { id: 24, label: "Swedish" },
  da: { id: 25, label: "Danish" },
  "da-DK": { id: 25, label: "Danish" },
  fi: { id: 26, label: "Finnish" },
  "fi-FI": { id: 26, label: "Finnish" },
  sk: { id: 28, label: "Slovak" },
  "sk-SK": { id: 28, label: "Slovak" },
  hr: { id: 29, label: "Croatian" },
  "hr-HR": { id: 29, label: "Croatian" },
  bg: { id: 30, label: "Bulgarian" },
  "bg-BG": { id: 30, label: "Bulgarian" },
  lt: { id: 31, label: "Lithuanian" },
  "lt-LT": { id: 31, label: "Lithuanian" },
  th: { id: 32, label: "Thai" },
  "th-TH": { id: 32, label: "Thai" },
  vi: { id: 33, label: "Vietnamese" },
  "vi-VN": { id: 33, label: "Vietnamese" },
  et: { id: 60, label: "Estonian" },
  "et-EE": { id: 60, label: "Estonian" },
  lv: { id: 61, label: "Latvian" },
  "lv-LV": { id: 61, label: "Latvian" },
  sl: { id: 62, label: "Slovenian" },
  "sl-SI": { id: 62, label: "Slovenian" },
  he: { id: 64, label: "Hebrew" },
  "he-IL": { id: 64, label: "Hebrew (Israel)" },
  "fr-CA": { id: 100, label: "French (Canada)" },
  auto: { id: 101, label: "Auto-detect" },
  mt: { id: 102, label: "Maltese" },
  "mt-MT": { id: 102, label: "Maltese" },
  nb: { id: 103, label: "Norwegian Bokmål" },
  "nb-NO": { id: 103, label: "Norwegian Bokmål" },
  nn: { id: 104, label: "Norwegian Nynorsk" },
  "nn-NO": { id: 104, label: "Norwegian Nynorsk" },
};

export const NEMOTRON_AUTO_LANGUAGE_ID = NEMOTRON_LANGUAGE_BY_CODE.auto.id;

export const resolveNemotronLanguageId = (code: string | undefined): number => {
  if (!code) return NEMOTRON_AUTO_LANGUAGE_ID;
  return NEMOTRON_LANGUAGE_BY_CODE[code]?.id ?? NEMOTRON_AUTO_LANGUAGE_ID;
};
